### ISSUE TITLE
Automated Docker Build

### ISSUE THREAD

**Issue by staaldraad** [staaldraad/tcpprox#2]
As suggested by @pataquets 

> Optional improvement to come (maybe in another issue):
 Create an 'official', based on your repo, automated build at Docker Hub for the image: 
 https://docs.docker.com/docker-hub/builds/ . Just requires a free Docker Hub account and a following a 
 quick 'Create automated build' process. I'll be happy to help on it, if needed.
 If an 'official' public image is available, I can submit my demo/testing Docker Compose manifest 
 demo'ing tcpprox in front of a memcached, to serve as an example (now it refers to my user's Docker 
 Hub image).

**Comment by pataquets** [comment]
@staaldraad: Bump.
There have been commits since then, which would be easily available if distributed via Docker.
You can also set it to create image versions based on git tags.
Should not be more than a few minutes of clicking through the create automated build pages at Docker Hub.
Let me know if I can be of any help. Unfortunately can't set up one myself, since it needs owner permission on the repo to link it.

**Comment by staaldraad** [comment]
Hey @pataquets - I thought I'd done this (hence the updated Dockerfile etc) and then got distracted by other things (finding a vuln in the build system) :joy: 

Setup the automated build, waiting for it to finish building but should be here soon: https://hub.docker.com/r/staaldraad/tcpprox

**Comment by staaldraad** [comment]
![screenshot 2019-02-10 at 16 19 39](https://user-images.githubusercontent.com/4200832/52535546-f8b83980-2d4f-11e9-8221-f95ea7762010.png)

**Comment by staaldraad** [comment]
Thanks again for the idea @pataquets 🚀 and sorry it took so long to do. It was all setup, I just had to renable the build linking and make the image public on Docker Hub.

**Comment by pataquets** [comment]
Awesome!!
Nothing to be sorry of. Happy to be helpful and thanks for sharing.
